#ifndef _FONTRUS_h_
#define _FONTRUS_h_

#include <Adafruit_GFX.h>>
#include <Bahamas10.h>
#include <Bahamas12.h>
#include <Bahamas14.h>
#include <Bahamas16.h>
#include <Bahamas18.h>
#include <Bahamas6.h>
#include <Bahamas7.h>
#include <Bahamas8.h>
#include <Bahamas9.h>
#include <Bat10.h>
#include <Bat5.h>
#include <Bat6.h>
#include <Bat7.h>
#include <Bat8.h>
#include <Bat9.h>
#include <Cooper10.h>
#include <Cooper12.h>
#include <Cooper14.h>
#include <Cooper16.h>
#include <Cooper18.h>
#include <Cooper6.h>
#include <Cooper7.h>
#include <Cooper8.h>
#include <Cooper9.h>
#include <CourierCyr10.h>
#include <CourierCyr12.h>
#include <CourierCyr14.h>
#include <CourierCyr16.h>
#include <CourierCyr18.h>
#include <CourierCyr6.h>
#include <CourierCyr7.h>
#include <CourierCyr8.h>
#include <CourierCyr9.h>
#include <Crystal10.h>
#include <Crystal12.h>
#include <Crystal14.h>
#include <Crystal16.h>
#include <Crystal18.h>
#include <Crystal6.h>
#include <Crystal7.h>
#include <Crystal8.h>
#include <Crystal9.h>
#include <CrystalNormal10.h>
#include <CrystalNormal12.h>
#include <CrystalNormal14.h>
#include <CrystalNormal16.h>
#include <CrystalNormal18.h>
#include <CrystalNormal6.h>
#include <CrystalNormal7.h>
#include <CrystalNormal8.h>
#include <CrystalNormal9.h>
// #include <fontrus.h>
#include <FreeMono10.h>
#include <FreeMono12.h>
#include <FreeMono14.h>
#include <FreeMono16.h>
#include <FreeMono18.h>
#include <FreeMono6.h>
#include <FreeMono7.h>
#include <FreeMono8.h>
#include <FreeMono9.h>
#include <FreeMonoBold10.h>
#include <FreeMonoBold12.h>
#include <FreeMonoBold14.h>
#include <FreeMonoBold16.h>
#include <FreeMonoBold18.h>
#include <FreeMonoBold6.h>
#include <FreeMonoBold7.h>
#include <FreeMonoBold8.h>
#include <FreeMonoBold9.h>
#include <FreeMonoBoldOblique10.h>
#include <FreeMonoBoldOblique12.h>
#include <FreeMonoBoldOblique14.h>
#include <FreeMonoBoldOblique16.h>
#include <FreeMonoBoldOblique18.h>
#include <FreeMonoBoldOblique6.h>
#include <FreeMonoBoldOblique7.h>
#include <FreeMonoBoldOblique8.h>
#include <FreeMonoBoldOblique9.h>
#include <FreeMonoOblique10.h>
#include <FreeMonoOblique12.h>
#include <FreeMonoOblique14.h>
#include <FreeMonoOblique16.h>
#include <FreeMonoOblique18.h>
#include <FreeMonoOblique6.h>
#include <FreeMonoOblique7.h>
#include <FreeMonoOblique8.h>
#include <FreeMonoOblique9.h>
#include <FreeSans10.h>
#include <FreeSans12.h>
#include <FreeSans14.h>
#include <FreeSans16.h>
#include <FreeSans18.h>
#include <FreeSans6.h>
#include <FreeSans7.h>
#include <FreeSans8.h>
#include <FreeSans9.h>
#include <FreeSansBold10.h>
#include <FreeSansBold12.h>
#include <FreeSansBold14.h>
#include <FreeSansBold16.h>
#include <FreeSansBold18.h>
#include <FreeSansBold6.h>
#include <FreeSansBold7.h>
#include <FreeSansBold8.h>
#include <FreeSansBold9.h>
#include <FreeSansBoldOblique10.h>
#include <FreeSansBoldOblique12.h>
#include <FreeSansBoldOblique14.h>
#include <FreeSansBoldOblique16.h>
#include <FreeSansBoldOblique18.h>
#include <FreeSansBoldOblique6.h>
#include <FreeSansBoldOblique7.h>
#include <FreeSansBoldOblique8.h>
#include <FreeSansBoldOblique9.h>
#include <FreeSansOblique10.h>
#include <FreeSansOblique12.h>
#include <FreeSansOblique14.h>
#include <FreeSansOblique16.h>
#include <FreeSansOblique18.h>
#include <FreeSansOblique6.h>
#include <FreeSansOblique7.h>
#include <FreeSansOblique8.h>
#include <FreeSansOblique9.h>
#include <FreeSerif10.h>
#include <FreeSerif12.h>
#include <FreeSerif14.h>
#include <FreeSerif16.h>
#include <FreeSerif18.h>
#include <FreeSerif6.h>
#include <FreeSerif7.h>
#include <FreeSerif8.h>
#include <FreeSerif9.h>
#include <FreeSerifBold10.h>
#include <FreeSerifBold12.h>
#include <FreeSerifBold14.h>
#include <FreeSerifBold16.h>
#include <FreeSerifBold18.h>
#include <FreeSerifBold6.h>
#include <FreeSerifBold7.h>
#include <FreeSerifBold8.h>
#include <FreeSerifBold9.h>
#include <FreeSerifBoldItalic10.h>
#include <FreeSerifBoldItalic12.h>
#include <FreeSerifBoldItalic14.h>
#include <FreeSerifBoldItalic16.h>
#include <FreeSerifBoldItalic18.h>
#include <FreeSerifBoldItalic6.h>
#include <FreeSerifBoldItalic7.h>
#include <FreeSerifBoldItalic8.h>
#include <FreeSerifBoldItalic9.h>
#include <FreeSerifItalic10.h>
#include <FreeSerifItalic12.h>
#include <FreeSerifItalic14.h>
#include <FreeSerifItalic16.h>
#include <FreeSerifItalic18.h>
#include <FreeSerifItalic6.h>
#include <FreeSerifItalic7.h>
#include <FreeSerifItalic8.h>
#include <FreeSerifItalic9.h>
#include <TimesNRCyr10.h>
#include <TimesNRCyr12.h>
#include <TimesNRCyr14.h>
#include <TimesNRCyr16.h>
#include <TimesNRCyr18.h>
#include <TimesNRCyr6.h>
#include <TimesNRCyr7.h>
#include <TimesNRCyr8.h>
#include <TimesNRCyr9.h>

#endif
